### ISSUE TITLE
Send Class 0 Flash SMS

### ISSUE THREAD

**Issue by ozone0** [futomi/node-sms-transceiver#1]
Thanks a lot for the module. I'm developing software for rural communication in Ghana, West Africa. I tried many SMS modules and faced all sorts of problems until I came across your work. 

Please how can I send a Class 0 or Flash SMS?

Regards.

**Comment by futomi** [comment]
This module does not support Flash SMS (Class 0).

**Comment by ozone0** [comment]
Thanks for the reply. Bests.
